function Level (options) {
  this.x = options.x;
  this.y = options.y;

  this.gameObjects = [
    new Outline({context: options.context, image: options.image, x: this.x, y: this.y}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 48, y: this.y + 48, width: 96, height: 72}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 168, y: this.y + 48, width: 120, height: 72}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 384, y: this.y + 48, width: 120, height: 72}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 528, y: this.y + 48, width: 96, height: 72}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 48, y: this.y + 144, width: 96, height: 48}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 528, y: this.y + 144, width: 96, height: 48}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 168, y: this.y + 360, width: 48, height: 120}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 456, y: this.y + 360, width: 48, height: 120}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 168, y: this.y + 504, width: 120, height: 48}),
    new Rectangle({context: options.context, image: options.image, x: this.x + 384, y: this.y + 504, width: 120, height: 48}),
    new TShape({context: options.context, image: options.image, x: this.x + 240, y: this.y + 144}),
    new TShape({context: options.context, image: options.image, x: this.x + 240, y: this.y + 432}),
    new TShape({context: options.context, image: options.image, x: this.x + 240, y: this.y + 576}),
    new GhostBox({context: options.context, image: options.image, x: this.x + 240, y: this.y + 288}),
    new HookShape1({context: options.context, image: options.image, x: this.x + 48, y: this.y + 504}),
    new HookShape2({context: options.context, image: options.image, x: this.x + 528, y: this.y + 504}),
    new InvertedT1({context: options.context, image: options.image, x: this.x + 48, y: this.y + 576}),
    new InvertedT2({context: options.context, image: options.image, x: this.x + 384, y: this.y + 576}),
    new FlippedT1({context: options.context, image: options.image, x: this.x + 168, y: this.y + 144}),
    new FlippedT2({context: options.context, image: options.image, x: this.x + 384, y: this.y + 144})
  ];

  this.pellets = [
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 168, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 192, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 456, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 480, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 24}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 48}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 72}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 96}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 168, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 192, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 312, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 336, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 456, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 480, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 120}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 144}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 168}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 192}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 216}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 216}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 240}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 240}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 264}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 264}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 288}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 288}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 312}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 312}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 336}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 336}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 360}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 360}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 384}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 384}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 408}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 408}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 432}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 432}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 456}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 456}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 168, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 192, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 456, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 480, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 480}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 504}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 528}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 168, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 192, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 456, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 480, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 552}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 576}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 600}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 624}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 648}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 648}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 648}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 648}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 672}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 672}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 672}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 672}),
    new Pellet({context: options.context, image: options.image, x: this.x + 24, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 48, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 72, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 96, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 120, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 144, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 168, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 192, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 216, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 240, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 264, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 288, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 312, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 336, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 360, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 384, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 408, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 432, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 456, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 480, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 504, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 528, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 552, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 576, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 600, y: this.y + 696}),
    new Pellet({context: options.context, image: options.image, x: this.x + 624, y: this.y + 696}),
  ];
}

Level.prototype.draw = function () {
  for (var i = 0; i < this.gameObjects.length; i++) {
    this.gameObjects[i].draw();
  }
  for (var i = 0; i < this.pellets.length; i++) {
    this.pellets[i].draw();
  }
};

Level.prototype.update = function (pacman) {
  for (var i = this.pellets.length - 1; i >= 0; i--) {
    if (this.pellets[i].checkCollision(pacman)) {
      this.pellets.splice(i, 1);
    }
  }
};
