var Outline = (function () {
  Outline.prototype = new BackgroundObject();
  Outline.prototype.constructor = Outline;

  function Outline (options) {
    BackgroundObject.call(this, options);

    this.images = [
      {block: this.blocks.topLeft1, x: 0, y: 0},
      {block: this.blocks.topHorizontal1, x: 1, y: 0},
      {block: this.blocks.topHorizontal1, x: 2, y: 0},
      {block: this.blocks.topHorizontal1, x: 3, y: 0},
      {block: this.blocks.topHorizontal1, x: 4, y: 0},
      {block: this.blocks.topHorizontal1, x: 5, y: 0},
      {block: this.blocks.topHorizontal1, x: 6, y: 0},
      {block: this.blocks.topHorizontal1, x: 7, y: 0},
      {block: this.blocks.topHorizontal1, x: 8, y: 0},
      {block: this.blocks.topHorizontal1, x: 9, y: 0},
      {block: this.blocks.topHorizontal1, x: 10, y: 0},
      {block: this.blocks.topHorizontal1, x: 11, y: 0},
      {block: this.blocks.topHorizontal1, x: 12, y: 0},
      {block: this.blocks.topRightContinues1, x: 13, y: 0},
      {block: this.blocks.topLeftContinues1, x: 14, y: 0},
      {block: this.blocks.topHorizontal1, x: 15, y: 0},
      {block: this.blocks.topHorizontal1, x: 16, y: 0},
      {block: this.blocks.topHorizontal1, x: 17, y: 0},
      {block: this.blocks.topHorizontal1, x: 18, y: 0},
      {block: this.blocks.topHorizontal1, x: 19, y: 0},
      {block: this.blocks.topHorizontal1, x: 20, y: 0},
      {block: this.blocks.topHorizontal1, x: 21, y: 0},
      {block: this.blocks.topHorizontal1, x: 22, y: 0},
      {block: this.blocks.topHorizontal1, x: 23, y: 0},
      {block: this.blocks.topHorizontal1, x: 24, y: 0},
      {block: this.blocks.topHorizontal1, x: 25, y: 0},
      {block: this.blocks.topHorizontal1, x: 26, y: 0},
      {block: this.blocks.topRight1, x: 27, y: 0},
      {block: this.blocks.leftVertical1, x: 0, y: 1},
      {block: this.blocks.leftVertical2, x: 13, y: 1},
      {block: this.blocks.rightVertical2, x: 14, y: 1},
      {block: this.blocks.rightVertical1, x: 27, y: 1},
      {block: this.blocks.leftVertical1, x: 0, y: 2},
      {block: this.blocks.leftVertical2, x: 13, y: 2},
      {block: this.blocks.rightVertical2, x: 14, y: 2},
      {block: this.blocks.rightVertical1, x: 27, y: 2},
      {block: this.blocks.leftVertical1, x: 0, y: 3},
      {block: this.blocks.leftVertical2, x: 13, y: 3},
      {block: this.blocks.rightVertical2, x: 14, y: 3},
      {block: this.blocks.rightVertical1, x: 27, y: 3},
      {block: this.blocks.leftVertical1, x: 0, y: 4},
      {block: this.blocks.bottomLeft2, x: 13, y: 4},
      {block: this.blocks.bottomRight2, x: 14, y: 4},
      {block: this.blocks.rightVertical1, x: 27, y: 4},
      {block: this.blocks.leftVertical1, x: 0, y: 5},
      {block: this.blocks.rightVertical1, x: 27, y: 5},
      {block: this.blocks.leftVertical1, x: 0, y: 6},
      {block: this.blocks.rightVertical1, x: 27, y: 6},
      {block: this.blocks.leftVertical1, x: 0, y: 7},
      {block: this.blocks.rightVertical1, x: 27, y: 7},
      {block: this.blocks.leftVertical1, x: 0, y: 8},
      {block: this.blocks.rightVertical1, x: 27, y: 8},
      {block: this.blocks.bottomLeft1, x: 0, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 1, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 2, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 3, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 4, y: 9},
      {block: this.blocks.topRight2, x: 5, y: 9},
      {block: this.blocks.topLeft2, x: 22, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 23, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 24, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 25, y: 9},
      {block: this.blocks.bottomHorizontal1, x: 26, y: 9},
      {block: this.blocks.bottomRight1, x: 27, y: 9},
      {block: this.blocks.leftVertical1, x: 5, y: 10},
      {block: this.blocks.rightVertical1, x: 22, y: 10},
      {block: this.blocks.leftVertical1, x: 5, y: 11},
      {block: this.blocks.rightVertical1, x: 22, y: 11},
      {block: this.blocks.leftVertical1, x: 5, y: 12},
      {block: this.blocks.rightVertical1, x: 22, y: 12},
      {block: this.blocks.topHorizontal1, x: 0, y: 13},
      {block: this.blocks.topHorizontal1, x: 1, y: 13},
      {block: this.blocks.topHorizontal1, x: 2, y: 13},
      {block: this.blocks.topHorizontal1, x: 3, y: 13},
      {block: this.blocks.topHorizontal1, x: 4, y: 13},
      {block: this.blocks.bottomRight2, x: 5, y: 13},
      {block: this.blocks.bottomLeft2, x: 22, y: 13},
      {block: this.blocks.topHorizontal1, x: 23, y: 13},
      {block: this.blocks.topHorizontal1, x: 24, y: 13},
      {block: this.blocks.topHorizontal1, x: 25, y: 13},
      {block: this.blocks.topHorizontal1, x: 26, y: 13},
      {block: this.blocks.topHorizontal1, x: 27, y: 13},
      {block: this.blocks.bottomHorizontal1, x: 0, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 1, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 2, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 3, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 4, y: 15},
      {block: this.blocks.topRight2, x: 5, y: 15},
      {block: this.blocks.topLeft2, x: 22, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 23, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 24, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 25, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 26, y: 15},
      {block: this.blocks.bottomHorizontal1, x: 27, y: 15},
      {block: this.blocks.leftVertical1, x: 5, y: 16},
      {block: this.blocks.rightVertical1, x: 22, y: 16},
      {block: this.blocks.leftVertical1, x: 5, y: 17},
      {block: this.blocks.rightVertical1, x: 22, y: 17},
      {block: this.blocks.leftVertical1, x: 5, y: 18},
      {block: this.blocks.rightVertical1, x: 22, y: 18},
      {block: this.blocks.topLeft1, x: 0, y: 19},
      {block: this.blocks.topHorizontal1, x: 1, y: 19},
      {block: this.blocks.topHorizontal1, x: 2, y: 19},
      {block: this.blocks.topHorizontal1, x: 3, y: 19},
      {block: this.blocks.topHorizontal1, x: 4, y: 19},
      {block: this.blocks.bottomRight2, x: 5, y: 19},
      {block: this.blocks.bottomLeft2, x: 22, y: 19},
      {block: this.blocks.topHorizontal1, x: 23, y: 19},
      {block: this.blocks.topHorizontal1, x: 24, y: 19},
      {block: this.blocks.topHorizontal1, x: 25, y: 19},
      {block: this.blocks.topHorizontal1, x: 26, y: 19},
      {block: this.blocks.topRight1, x: 27, y: 19},
      {block: this.blocks.leftVertical1, x: 0, y: 20},
      {block: this.blocks.rightVertical1, x: 27, y: 20},
      {block: this.blocks.leftVertical1, x: 0, y: 21},
      {block: this.blocks.rightVertical1, x: 27, y: 21},
      {block: this.blocks.leftVertical1, x: 0, y: 22},
      {block: this.blocks.rightVertical1, x: 27, y: 22},
      {block: this.blocks.leftVertical1, x: 0, y: 23},
      {block: this.blocks.rightVertical1, x: 27, y: 23},
      {block: this.blocks.bottomLeftContinues2, x: 0, y: 24},
      {block: this.blocks.topHorizontal2, x: 1, y: 24},
      {block: this.blocks.topRight2, x: 2, y: 24},
      {block: this.blocks.topLeft2, x: 25, y: 24},
      {block: this.blocks.topHorizontal2, x: 26, y: 24},
      {block: this.blocks.bottomRightContinues2, x: 27, y: 24},
      {block: this.blocks.topLeftContinues2, x: 0, y: 25},
      {block: this.blocks.bottomHorizontal2, x: 1, y: 25},
      {block: this.blocks.bottomRight2, x: 2, y: 25},
      {block: this.blocks.bottomLeft2, x: 25, y: 25},
      {block: this.blocks.bottomHorizontal2, x: 26, y: 25},
      {block: this.blocks.topRightContinues2, x: 27, y: 25},
      {block: this.blocks.leftVertical1, x: 0, y: 26},
      {block: this.blocks.rightVertical1, x: 27, y: 26},
      {block: this.blocks.leftVertical1, x: 0, y: 27},
      {block: this.blocks.rightVertical1, x: 27, y: 27},
      {block: this.blocks.leftVertical1, x: 0, y: 28},
      {block: this.blocks.rightVertical1, x: 27, y: 28},
      {block: this.blocks.leftVertical1, x: 0, y: 29},
      {block: this.blocks.rightVertical1, x: 27, y: 29},
      {block: this.blocks.bottomLeft1, x: 0, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 1, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 2, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 3, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 4, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 5, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 6, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 7, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 8, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 9, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 10, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 11, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 12, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 13, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 14, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 15, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 16, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 17, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 18, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 19, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 20, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 21, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 22, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 23, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 24, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 25, y: 30},
      {block: this.blocks.bottomHorizontal1, x: 26, y: 30},
      {block: this.blocks.bottomRight1, x: 27, y: 30}
    ];

    this.boundingBoxes = [
      new BoundingBox(0, 0, 672, 12),
      new BoundingBox(324, 0, 24, 108),
      new BoundingBox(0, 0, 12, 324),
      new BoundingBox(0, 228, 132, 96),
      new BoundingBox(0, 372, 132, 96),
      new BoundingBox(0, 372, 12, 372),
      new BoundingBox(0, 588, 60, 24),
      new BoundingBox(0, 732, 672, 12),
      new BoundingBox(660, 0, 12, 324),
      new BoundingBox(540, 228, 132, 96),
      new BoundingBox(540, 372, 132, 96),
      new BoundingBox(660, 372, 12, 372),
      new BoundingBox(612, 588, 60, 24)
    ];
  }

  return Outline;
}());
